apiVersion: v1
kind: Service
metadata:
  labels:
    app: orbit-api-app
  name: orbit-api-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: orbit-api-app
  type: LoadBalancer
status:
  loadBalancer: {}
